# Generated by Django 4.2.29 on 2026-03-10 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rosterassignment',
            name='chore',
        ),
        migrations.RemoveField(
            model_name='rosterassignment',
            name='user',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='entered_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='direction',
            new_name='transaction_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='claim_status',
            field=models.CharField(choices=[('NONE', 'Not a Claim'), ('PENDING', 'Pending'), ('PAID', 'Paid Back')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_claim',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_source',
            field=models.CharField(blank=True, choices=[('FLAT', 'Flat Account/Card'), ('PERSONAL', 'Paid Personally'), ('TRANSFER', 'Bank Transfer')], max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reimbursed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reimbursed_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Chore',
        ),
        migrations.DeleteModel(
            name='RosterAssignment',
        ),
    ]
