# Generated by Django 4.2.29 on 2026-03-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0003_chore_rosterassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
