# Generated by Django 4.2.29 on 2026-03-11 09:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flat', '0005_transaction_paid_by_alter_transaction_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rosterassignment',
            options={'ordering': ['week_start', 'chore__name']},
        ),
        migrations.AlterUniqueTogether(
            name='rosterassignment',
            unique_together={('user', 'week_start')},
        ),
    ]
